version: "3.8"

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: orders_db
      MYSQL_USER: order_user
      MYSQL_PASSWORD: order_password
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - micro-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql-db
      PMA_PORT: 3306
      PMA_USER: order_user
      PMA_PASSWORD: order_password
    ports:
      - "8080:80"
    depends_on:
      - mysql-db
    networks:
      - micro-net

  service-registry:
   build:
     context: ./service-registrey
   container_name: service-registry
   ports:
      - "8761:8761"
   networks:
      - micro-net

# api gateway configuration
  api-gateway:
    build:
      context: ./ApiGateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8811:8811"
    depends_on:
      - service-registry
    networks:
      - micro-net
    environment:
      - EUREKA_SERVER_URL=http://service-registry:8761/eureka

  config-server:
    build:
        context: ./ConfigServer
    container_name: config-server
    ports:
      - "8853:8853"
    depends_on:
      - service-registry
    networks:
      - micro-net
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka


  order-service:
    build:
      context: ./orderService/orderService
      dockerfile: Dockerfile
    container_name: order-service
    ports:
      - "8852:8852"
    depends_on:
      - service-registry
      - config-server
      - mysql-db
    networks:
      - micro-net
    environment:
      - CONFIG_SERVER_URL=http://config-server:8853
      - EUREKA_SERVER_URL=http://service-registry:8761/eureka

volumes:
    service-registry-data:
    config-server-data:
    mysql-data:


networks:
  micro-net:
    driver: bridge